### ISSUE TITLE
Does not work correctly with Docker Compose 1.29.2

### ISSUE THREAD

**Issue by sergio-fry** [sergio-fry/devup#68]
This version is latest for linux now

**Comment by IgorShum** [comment]
Name                   Command               State                      Ports                   
----------------------------------------------------------------------------------------------------
eb_forms_db_1   docker-entrypoint.sh postgres    Up       0.0.0.0:49153->5432/tcp,:::49153->5432/tcp
rabbitmq        docker-entrypoint.sh rabbi ...   Exit 1

**Comment by sergio-fry** [comment]
Actually it is not a bug: serivices rabbitmq can't be started because of some error.
